### ISSUE TITLE
Preprocessing Issue

### ISSUE THREAD

**Issue by kaliaanup** [nbalepur/DynaMiTE#1]
While running it on debate data I got the following issues

Traceback (most recent call last):
  File "/Users/akalia/Research_Papers/Real-Time-Event-Extraction/Dynamite/DynaMiTE-main/preprocessing/preprocess.py", line 210, in <module>
    emb, pmi_samples, cx, cxy, vocab = create_pmi(year_texts_phrase[year])
  File "/Users/akalia/Research_Papers/Real-Time-Event-Extraction/Dynamite/DynaMiTE-main/preprocessing/preprocess.py", line 191, in create_pmi
    PMI = csc_matrix((data, (rows, cols)))
  File "/Users/akalia/miniforge3/lib/python3.9/site-packages/scipy/sparse/_compressed.py", line 53, in __init__
    self._coo_container(arg1, shape=shape, dtype=dtype)
  File "/Users/akalia/miniforge3/lib/python3.9/site-packages/scipy/sparse/_coo.py", line 148, in __init__
    raise ValueError('cannot infer dimensions from zero '
ValueError: cannot infer dimensions from zero sized index arrays

So far I have generated the following files.

data.csv
phrase_text.txt
text.txt
wordIDHash.csv
wordPairPMI_2012.csv
wordPairPMI_2013.csv
wordPairPMI_2014.csv
wordPairPMI_2015.csv

**Comment by nbalepur** [comment]
Hi kaliaanup, I believe this should indicate that your text corpus is empty at the next time step (presumably 2016). Is one of your years in the corpus 2016? If this isn't your issue, I can also try looking at your specific dataset!

**Comment by kaliaanup** [comment]
Sorry for delay. Yes you are right. I downloaded the file from here. https://www.kaggle.com/datasets/unitednations/un-general-debates. These are all the years of data they have. 

[1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015]

So apparently they don't have data for 2016 and 2017. Also they have 7507 text values.

Can you please provide the dataset that you guys used to replicate the work?

**Comment by nbalepur** [comment]
I finished this project at my undergraduate institution so I do not the data readily accessible. I'll ask my co-authors who are still at UIUC and I'll get back to you!

But I believe the data you downloaded should be correct. You can set `all_times = [1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015]` meanwhile to account for the missing years!

**Comment by nbalepur** [comment]
We've uploaded the datasets to huggingface: [nbalepur/DynaMiTE](https://huggingface.co/datasets/nbalepur/DynaMiTE)

The entire UN dataset is also uploaded (1.43M rows) but I believe we just took a random sample of it to obtain the 250k number

**Comment by kaliaanup** [comment]
Thanks a lot. I am assuming 2012-2022 represents arxiv data. What does 1-20 represents?

**Comment by nbalepur** [comment]
I'm assuming you mean 11 to 20 for Newspop! The numbers are in ascending order based on the time span, the actual number doesn't matter too much. Newspop is from Oct. 2015 to Jul. 2016 (in the paper), so 11 is October 2015 and 20 is July 2016

**Comment by kaliaanup** [comment]
got it. So 1-10 is un-debates, 11-20 is newspop, 2012-2017 is arxiv? If yes feel free to add this to your README. It's super useful.

**Comment by nbalepur** [comment]
Thats exactly right, thanks for the feedback! Ill update the README accordingly
