### ISSUE TITLE
Memory Issue for Arxiv [OOM error while preprocessing]

### ISSUE THREAD

**Issue by kaliaanup** [nbalepur/DynaMiTE#2]
I am running the preprocess.py on a 16GB memory. After a while it gives OOM issue. Is there a memory efficient code you have? Or you have tried to make it run with a larger memory.

**Comment by nbalepur** [comment]
Hi kaliaanup, we ran this on a server that had a lot of memory. I will find out the specific value. One way to lower the memory requirements is to increase the frequency threshold for when we consider words to include in the corpus
